package com.ayudaencasa.user.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="user")
public class User implements Serializable {
    @DynamoDBHashKey (attributeName = "uId")
    @DynamoDBAutoGeneratedKey
    private String uId;
    @DynamoDBAttribute
    private String mail;
    @DynamoDBAttribute
    private String mailAlt;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String photo;
    @DynamoDBAttribute
    private int telephone;



    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getMailAlt() {
        return mailAlt;
    }

    public void setMailAlt(String mailAlt) {
        this.mailAlt = mailAlt;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public int getTelephone() {
        return telephone;
    }

    public void setTelephone(int telephone) {
        this.telephone = telephone;
    }

    public String getuId() {
        return uId;
    }

    public void setuId(String uId) {
        this.uId = uId;
    }
}
